# This file can be used to configure enum attributes in the model.
# For example to add different allowed values for Abbreviation::Type
# you can change the values under abbreviation => type
#
# NOTE: All the keys in this file are needed for the script to run
#       and should not be removed. You can change the values but atleast
#       one option should be present in each list.

concept_source:
  status:
    - identical
    - similar # in iev-data
    - modified
    - restyle
    - context-added
    - generalisation
    - specialisation
    - unspecified
    - related # in iev-data
    - not_equal # in iev-data
  type:
    - authoritative
    - lineage

designation:
  base:
    normative_status:
      - preferred
      - deprecated
      - admitted
      - obsoleto # in iev-data
      - напуштен # in iev-data
      - <símbolo> # in iev-data
      - 티에스 # in iev-data
      - prąd startowy # in iev-data

related_concept:
  type:
    - deprecates
    - supersedes
    - superseded_by
    - narrower
    - broader
    - equivalent
    - compare
    - contrast
    - see

abbreviation:
  type:
    - truncation
    - acronym
    - initialism

grammar_info:
  boolean_attribute:
    - preposition
    - participle
    - adj
    - verb
    - adverb
    - noun
  gender:
    - m
    - f
    - n
    - c
  number:
    - singular
    - dual
    - plural

concept:
  status:
    - draft
    - not_valid
    - valid
    - superseded
    - retired

concept_date:
  type:
    - accepted
    - amended
    - retired
