:glossarist_model_url: https://github.com/glossarist/concept-model/tree/main
:glossarist_model_v2_schema_url: https://github.com/glossarist/concept-model/tree/main/yaml_schemas

= Glossarist

Glossarist gem implements the {glossarist_model_url}[Glossarist model] in ruby. All the entities in the model are available as classes and all the attributes are available as methods of those classes.
This gem also allows you to read/write data to concept dataset or create your own collection and save that to glossarist model V2 dataset.

The YAML schema for `concept` and `localized_concept` is available at {glossarist_model_v2_schema_url}[Concept model/yaml_schemas]

== Installation

Add this line to your application's Gemfile:

[,ruby]
----
gem 'glossarist'
----

And then execute:
[,bash]
----
bundle install
----

Or install it yourself as:
[,bash]
----
gem install glossarist
----

== Usage

=== Reading a Glossarist model V2 from files

Glossarist model V2 dataset is a collection of concepts and their localized
concepts in the form of YAML files.

The storage structure of the dataset has 2 forms:

1. Each concept is stored in a concept YAML file and its localized concepts are
stored in separate YAML files. The concept files are stored in the `concept`
folder and its localized concepts are stored in the `localized_concept` folder.
2. Each concept and its related localized concepts are stored in a single YAML
file. These concept files are stored directly in the specified path.

To load the glossarist model V2 dataset:

[,ruby]
----
collection = Glossarist::ManagedConceptCollection.new
collection.load_from_files("path/to/glossarist-v2-dataset")
----

=== Writing a Glossarist model V2 to files

To write the glossarist model V2 dataset to files:

[,ruby]
----
# load the collection from files
collection = Glossarist::ManagedConceptCollection.new
collection.load_from_files("path/to/glossarist-v2-dataset")

# ... Update the collection ...

collection.save_to_files("path/to/glossarist-v2-dataset")
----

To write the glossarist model V2 dataset with concepts and their
localized concepts grouped into single files:

[,ruby]
----
# load the collection from files
collection = Glossarist::ManagedConceptCollection.new
collection.load_from_files("path/to/glossarist-v2-dataset")

# ... Update the collection ...

collection.save_grouped_concepts_to_files("path/to/glossarist-v2-dataset")
----

=== ManagedConceptCollection

This is a collection for <<managed-concept,managed concepts>>. It includes the ruby 'Enumerable' module.

[,ruby]
----
collection = Glossarist::ManagedConceptCollection.new
----

[[id,managed-concept]]
=== ManagedConcept

Following fields are available for ManagedConcept:

id:: String identifier for the concept
uuid:: UUID for the concept
related:: Array of <<related-concept,RelatedConcept>>
status:: Enum for the normative status of the term.
dates:: Array of <<concept-date,ConceptDate>>
localized_concepts:: Hash of all localizations where keys are language codes and values are uuid of the localized concept.
groups:: Array of groups in string format
localizations:: Hash of all localizations for this concept where keys are language codes and values are instances of <<localized-concept,LocalizedConcept>>.

There are two ways to initialize and populate a managed concept

1. Setting the fields by using a hash while initializing
+
[,ruby]
----
concept = Glossarist::ManagedConcept.new({
  "data" => {
    "id" => "123",
    "localized_concepts" => {
      "ara" => "<uuid>",
      "eng" => "<uuid>"
    },
    "localizations" => <Array of localized concepts or localized concept hashes>,
    "groups" => [
      "foo",
      "bar",
    ],
  },
})
----

2. Setting the fields after creating an object
+
[,ruby]
----
concept = Glossarist::ManagedConcept.new
concept.id = "123"
concept.groups = ["foo", "bar"]
concept.localizations = <Array of localized concepts or localized concept hashes>
----

[[id,localized-concept]]
=== LocalizedConcept

Localizations of the term to different languages.

Localized concept has the following fields

id:: An optional identifier for the term, to be used in cross-references.
uuid:: UUID for the concept
designations:: Array of <<designation,Designations>> under which the term being defined is known. This method will also accept an array of hashes for designation and will convert them to their respective classes.
domain:: An optional semantic domain for the term being defined, in case the term is ambiguous between several semantic domains.
subject:: Subject of the term.
definition:: Array of <<detailed-definition,Detailed Definition>> of the term.
non_verb_rep:: Array of <<non-verbal,non-verbal>> representations used to help define the term.
notes:: Zero or more notes about the term. A note is in <<detailed-definition,Detailed Definition>> format.
examples:: Zero or more examples of how the term is to be used in <<detailed-definition,Detailed Definition>> format.
language_code:: The language of the localization, as an ISO-639 3-letter code.
entry_status:: Entry status of the concept. Must be one of the following: +notValid+, +valid+, +superseded+, +retired+.
classification:: Classification of the concept. Must be one of the following: +preferred+, +admitted+, +deprecated+.

[[id,designation]]
=== Designation::Base

A name under which a managed term is known.

Methods::
  `from_h(options)`::: Creates a new designation instance based on the specified type.

Parameters::
  * options (Hash) - The options for creating the designation.
  * "type" (String) - The type of designation (expression, symbol, abbreviation, graphical_symbol, letter_symbol). Note: type key should be string and not a symbol so { type: "expression" } will not work.
  * Additional options depend on the specific designation type.

Returns::
  Designation::{type}::: A new instance of specified type. e.g `Glossarist::Designation::Base.from_h("type" => "expression")` will return `Glossarist::Designation::Expression`

Example
[,ruby]
----
# Example usage of Designation::Base class

attributes_for_expression = { designation: "foobar", geographical_area: "abc", normative_status: "status" }
designation_expression = Designation::Base.from_h({ "type" => "expression" }.merge(attributes_for_expression))

attributes_for_abbreviation = { designation: "foobar", geographical_area: "abc", normative_status: "status", international: true }
designation_abbreviation = Designation::Base.from_h({ "type" => "abbreviation" }.merge(attributes_for_abbreviation))

----

[[id,related-concept]]
=== RelatedConcept

A term related to the current term.

Following fields are available for the Related Concept

type:: An enum to denote the relation of the term to the current term.
content:: The designation of the related term.
ref:: A <<citation, citation>> of the related term, in a Termbase.

There are two ways to initialize and populate a related concept

1. Setting the fields by using a hash while initializing
+
[,ruby]
----
related_concept = Glossarist::RelatedConcept.new({
  content: "Test content",
  type: :supersedes,
  ref: <concept citation>
})
----

2. Setting the fields after creating an object
+
[,ruby]
----
related_concept = Glossarist::RelatedConcept.new
related_concept.type = "supersedes"
related_concept.content = "designation of the related concept"
related_concept.ref = <Citation object>
----

[[id,concept-date]]
=== Concept Date

A date relevant to the lifecycle of the managed term.

Following fields are available for the Concept Date

- date: The date associated with the managed term in Iso8601Date format.
- type: An enum to denote the event which occured on the given date and associated with the lifecycle of the managed term.

There are two ways to initialize and populate a concept date

1. Setting the fields by using a hash while initializing
+
[,ruby]
----
concept_date = Glossarist::ConceptDate.new({
  date: "2010-11-01T00:00:00+00:00",
  type: :accepted,
})
----

2. Setting the fields after creating an object
+
[,ruby]
----
concept_date = Glossarist::ConceptDate.new
concept_date.type = :accepted
concept_date.date = "2010-11-01T00:00:00+00:00"
----

[[id,detailed-definition]]
=== DetailedDefinition

A definition of the managed term.

It has the following attributes:

content:: The text of the definition of the managed term.
sources:: List of Bibliographic references(<<citation,Citation>>) for this particular definition of the managed term.

There are two ways to initialize and populate a detailed definition

1. Setting the fields by using a hash while initializing
+
[,ruby]
----
detailed_definition = Glossarist::DetailedDefinition.new({
  content: "plain text reference",
  sources: [<list of citations>],
})
----

2. Setting the fields after creating an object
+
[,ruby]
----
detailed_definition = Glossarist::DetailedDefinition.new
detailed_definition.content = "plain text reference",
detailed_definition.sources = [<list of citations>]
----

[[id,citation]]
=== Citation

Citation can be either structured or unstructured. A citation is structured if its reference contains one or all of the following keys `{ id: "id", source: "source", version: "version"}` and is unstructured if its reference is plain text. This also has 2 methods `structured?` and `plain?` to check if citation is structured or not.

Citation has the following attributes.

ref:: A hash or string based on type of citation. Hash if citation is structured or string if citation is plain.
clause:: Referred clause of the document.
link:: Link to document.

There are two ways to initialize and populate a Citation

1. Setting the fields by using a hash while initializing
+
[,ruby]
----
# Unstructured Citation
citation = Glossarist::Citation.new({
  ref: "plain text reference",
  clause: "clause",
  link: "link",
})

# Structured Citation
citation = Glossarist::Citation.new({
  ref: { id: "123", source: "source", version: "1.1" },
  clause: "clause",
  link: "link",
})
----

2. Setting the fields after creating an object
+
[,ruby]
----
citation = Glossarist::Citation.new
citation.ref = <plain or structured ref>
citation.clause = "some clause"
----

=== NonVerbRep

Non-verbal Representation have the following fields

image:: An image used to help define a term.
table:: A table used to help define a term.
formula:: A formula used to help define a term.
sources:: Bibliographic <<concept-source,concept source>> for the non-verbal representation of the term.

[[id,concept-source]]
=== ConceptSource

Concept Source has the following fields

status:: The status of the managed term in the present context, relative to the term as found in the bibliographic source.
type:: The type of the managed term in the present context.
origin:: The bibliographic <<citation,citation>> for the managed term. This is also aliased as `ref`.
modification:: A description of the modification to the cited definition of the term, if any, as it is to be applied in the present context.


== Commands

=== generate_latex

Convert Concepts to Latex format.

[,bash]
----
glossarist generate_latex -p PATH_TO_CONCEPTS
----

Options:
[cols="1,1"]
|===
|p, --concepts-path
|Path to yaml concepts directory

|l, --latex-concepts
|File path having list of concepts that should be converted to LATEX format

|o, --output-file
|Output file path

|e, --extra-attributes
|List of extra attributes that are not in standard Glossarist Concept model
|===

=== package

Create a `.gcr` ZIP archive from a concept dataset.

[,bash]
----
glossarist package DIR -o output.gcr --shortname mydataset --version 1.0.0 --uri-prefix urn:iso:std:iso:19111
----

Options:
[cols="1,1"]
|===
|o, --output (required)
|Output `.gcr` file path

|--shortname (required)
|Machine-readable dataset shortname (e.g. `iev`, `iso19111`)

|--version (required)
|Semantic version (e.g. `1.0.0`)

|--title
|Human-readable dataset title

|--description
|Dataset description

|--owner
|Dataset owner

|--register-yaml
|Path to register.yaml to include in package

|--uri-prefix
|URI namespace this dataset provides (e.g. `urn:iec:std:iec:60050`)

|--tags
|Tags for the dataset

|--compiled-formats
|Comma-separated compiled formats to bundle (tbx,jsonld,turtle,jsonl)

|--concept-uri-template
|URI template for concept URIs
|===

Ruby API:
[,ruby]
----
GcrPackage.create_from_directory(
  "path/to/dataset",
  output: "output.gcr",
  shortname: "mydataset",
  version: "1.0.0",
  uri_prefix: "urn:iso:std:iso:19111",
  compiled_formats: ["jsonld", "turtle"],
)
----

=== export

Export concepts in machine-readable formats.

[,bash]
----
glossarist export PATH --format json --output DIR
glossarist export PATH --format jsonld --output DIR --shortname isotc211
glossarist export PATH --format turtle --output DIR
glossarist export PATH --format tbx --output DIR --shortname isotc211
glossarist export PATH --format jsonl --output DIR
glossarist export package.gcr --format json --output DIR
----

The path can be either a concept dataset directory or a `.gcr` file. When exporting from a `.gcr`, the `shortname` and `uri_prefix` are automatically resolved from the package metadata.

==== Output Formats

[cols="1,2,1"]
|===
|Format |Output |Files

|`json`
|Per-concept JSON files
|`{concept_id}.json`

|`tbx`
|Single TBX-XML document (ISO 30042:2019)
|`{shortname}.tbx.xml`

|`jsonld`
|Single JSON-LD file with `@graph`
|`{shortname}.jsonld`

|`turtle`
|Single Turtle file with all concept triples
|`{shortname}.ttl`

|`jsonl`
|JSONL file with one JSON-LD object per line
|`{shortname}.jsonl`
|===

Options:
[cols="1,1"]
|===
|--format (required)
|Output format: `json`, `tbx`, `jsonld`, `turtle`, or `jsonl`

|o, --output (required)
|Output directory

|--shortname
|Dataset shortname for concept ID prefixing

|--uri-prefix
|URI/URN prefix for the dataset

|--site-url
|Base URL of the glossarist site

|--title
|Dataset title for document header
|===

Ruby API:
[,ruby]
----
# Export to JSON-LD
cmd = Glossarist::CLI::ExportCommand.new("path/to/dataset",
  format: "jsonld", output: "/tmp/export", shortname: "isotc211")
cmd.run

# Transform a single concept to SKOS
skos = Glossarist::Transforms::ConceptToSkosTransform.transform(concept)
puts skos.to_jsonld
puts skos.to_turtle
----

=== validate

Validate a dataset directory or `.gcr` file for schema compliance.

[,bash]
----
glossarist validate PATH
glossarist validate PATH --reference-path path/to/gcrs/
----

Options:
[cols="1,1"]
|===
|--strict
|Treat warnings as errors

|--format
|Output format: `text`, `json`, or `yaml`

|--reference-path
|Path to directory of `.gcr` files for cross-dataset reference validation
|===

Ruby API:
[,ruby]
----
result = DatasetValidator.new.validate("path/to/dataset")
result = DatasetValidator.new.validate("path/to/dataset", reference_path: "gcrs/")
result.valid?   # => true/false
result.errors   # => [...]
result.warnings # => [...]
----

=== upgrade

Upgrade a dataset to the current schema version.

[,bash]
----
glossarist upgrade SOURCE_DIR -o OUTPUT_DIR
----

== Glossarist Concept Repository (GCR)

A **GCR** (Glossarist Concept Repository) is a distributable, versioned ZIP archive containing glossary concepts and metadata. GCR packages are created from v2 datasets.

=== GCR Package Format

A `.gcr` file is a ZIP archive with the following structure:

----
metadata.yaml          # Package metadata
register.yaml          # Optional register information
concepts/              # Concept YAML files
  102-01-01.yaml
  200.yaml
----

=== Creating a GCR Package

CLI:
[,bash]
----
glossarist package path/to/v2-dataset -o mydataset-1.0.0.gcr \
  --shortname mydataset --version 1.0.0 --uri-prefix urn:iso:std:iso:19111
----

Ruby API:
[,ruby]
----
GcrPackage.create_from_directory(
  "path/to/v2-dataset",
  output: "mydataset-1.0.0.gcr",
  shortname: "mydataset",
  version: "1.0.0",
  uri_prefix: "urn:iso:std:iso:19111",
  title: "My Dataset",
  description: "A terminology dataset",
)
----

=== Loading a GCR Package

[,ruby]
----
pkg = GcrPackage.load("mydataset-1.0.0.gcr")
pkg.metadata     # => Hash with metadata fields
pkg.concepts     # => Array of concept hashes
----

=== GCR Metadata

Metadata fields in `metadata.yaml`:

[cols="1,1"]
|===
|shortname
|Machine-readable dataset identifier (e.g. `iev`)

|version
|Semantic version (e.g. `1.0.0`)

|title
|Human-readable title

|description
|Dataset description

|owner
|Dataset owner

|tags
|Array of tags

|concept_count
|Number of concepts in the package

|languages
|Array of language codes present

|created_at
|ISO 8601 timestamp of package creation

|glossarist_version
|Version of the Glossarist gem used

|schema_version
|Schema version of the package format

|uri_prefix
|URI namespace this dataset provides (e.g. `urn:iec:std:iec:60050`)

|external_references
|Array of `{uri: "..."}` for URI namespaces this dataset references
|===

=== GCR Statistics

[,ruby]
----
stats = GcrStatistics.from_concepts(concepts)
stats.total_concepts           # => 150
stats.languages                # => ["eng", "fra", "deu"]
stats.concepts_by_status       # => { "valid" => 140, "draft" => 10 }
stats.concepts_with_definitions # => 148
stats.concepts_with_sources    # => 130
----

== Concept Mentions

Concepts can reference other concepts within the same dataset (intra-set) or in different datasets (inter-set) using inline mention syntax. All mentions use double braces `{{...}}`.

=== Syntax

The concept mention syntax mirrors HTML `<a href="id">display_text</a>` — the display text is independent of the target concept's canonical designation.

[cols="1,2,2,2"]
|===
|Form |Syntax |Example |Resolution

|ID only
|`{{ID}}`
|`{{200}}`
|Intra-set: concept 200, auto-display

|ID + display
|`{{TEXT, ID}}`
|`{{geodetic latitude, 200}}`
|Intra-set: concept 200, custom display

|Designation
|`{{TEXT}}`
|`{{geodetic latitude}}`
|Intra-set: find by designation

|URN + display
|`{{TEXT, URN}}`
|`{{equality, urn:iec:std:iec:60050-102-01-01}}`
|Inter-set: resolve by URN

|URN only
|`{{URN}}`
|`{{urn:iec:std:iec:60050-102-01-01}}`
|Inter-set: resolve URN, auto-display
|===

=== URN Schemes

IEC URN (IEV):: `urn:iec:std:iec:60050-{code}` — source is `urn:iec:std:iec:60050`, concept_id is the IEV code
ISO URN (RFC 5141):: `urn:iso:std:iso:{std}:...:term:{id}` — source is `urn:iso:std:iso:{std}`, concept_id is the term ID

=== Extracting Mentions (Ruby API)

[,ruby]
----
extractor = ReferenceExtractor.new

# From a text string
refs = extractor.extract_from_text("See {{equality, urn:iec:std:iec:60050-102-01-01}} and {{lat, 200}}")
# => [ConceptReference(term: "equality", concept_id: "102-01-01",
#                      source: "urn:iec:std:iec:60050", ref_type: "urn"),
#     ConceptReference(term: "lat", concept_id: "200",
#                      source: nil, ref_type: "local")]

# From all text fields in a localized concept
refs = extractor.extract_from_localized(lc_hash)

# From all language blocks in a concept
refs = extractor.extract_from_concept_hash(concept_hash)
----

=== Resolving Mentions (Ruby API)

Resolution uses an adapter chain: route overrides → local → package → remote.

[,ruby]
----
resolver = ReferenceResolver.new

# Register the current dataset for intra-set resolution
resolver.register_self(concepts)

# Register co-loaded GCRs with their URI prefixes
resolver.register_package(iev_concepts, uri_prefix: "urn:iec:std:iec:60050")
resolver.register_package(iso_concepts, uri_prefix: "urn:iso:std:iso:19111")

# Add URI route overrides (e.g. author used wrong URI)
resolver.add_route(from: "urn:iso:std:iso:19115", to: "urn:iso:std:iso:19111")

# Resolve a single reference
ref = ConceptReference.new(term: "equality", concept_id: "102-01-01",
                           source: "urn:iec:std:iec:60050", ref_type: "urn")
resolver.resolve(ref)  # => concept hash

# Validate all references in a package
result = resolver.validate_all(concepts)
result.errors    # => structural errors
result.warnings  # => unresolvable references
----

=== GCR Collection & Routing

When multiple GCRs are placed together in a directory, a `collection.yaml` configures resolution:

[,yaml]
----
# collection.yaml
packages:
  - file: iev-2.0.0.gcr
  - file: iso19111-1.0.0.gcr

routes:
  - from: "urn:iso:std:iso:19115"
    to: "urn:iso:std:iso:19111"

remote:
  - uri_prefix: "urn:iec:std:iec:60050"
    endpoint: "https://vocabulary.example.org/api/concepts"
----

[,ruby]
----
resolver = ReferenceResolver.new
resolver.load_collection("path/to/gcr_collection/")
# Packages auto-registered with their uri_prefix from metadata
# Route overrides applied
# Remote endpoints registered
----

=== Resolution Adapters

The resolution framework uses a chain of adapters, each implementing `resolve(reference) → concept_hash | nil`:

LocalAdapter:: Resolves intra-set references by concept ID or designation lookup
PackageAdapter:: Resolves inter-set references by matching `source` URI to a GCR's `uri_prefix`
RouteAdapter:: Remaps incorrect source URIs before delegation
RemoteAdapter:: Resolves via HTTP to an online GCR endpoint

=== URN-to-HTTP Resolution

Concept mentions rendered as hyperlinks need HTTP URLs. The `UrnResolver` converts URNs to their canonical web locations:

[,ruby]
----
# Class-level convenience
url = UrnResolver.resolve("urn:iec:std:iec:60050-102-01-01")
# => "https://www.electropedia.org/iev/iev.nsf/display?openform&ievref=102-01-01"

url = UrnResolver.resolve("urn:iso:std:iso:19111:ed-3:v1:en:term:3.1.32")
# => "https://www.iso.org/obp/ui/#iso:std:iso:19111:ed-3:v1:en:term:3.1.32"

# Also accepts ConceptReference objects
ref = ConceptReference.new(term: "equality", concept_id: "102-01-01",
                           source: "urn:iec:std:iec:60050", ref_type: "urn")
url = UrnResolver.resolve(ref)
# => "https://www.electropedia.org/iev/iev.nsf/display?openform&ievref=102-01-01"
----

Built-in mappings:

[cols="1,1,1"]
|===
|URN Prefix |Target |Example URL

|`urn:iec:std:iec:60050-*`
|IEC Electropedia
|`electropedia.org/iev/iev.nsf/display?openform&ievref=102-01-01`

|`urn:iso:*`
|ISO Online Browsing Platform
|`iso.org/obp/ui/#iso:std:iso:19111:term:3.1.32`
|===

Register custom schemes:

[,ruby]
----
resolver = UrnResolver.new
resolver.register_scheme("urn:example:") do |urn|
  "https://example.org/concepts/#{urn.sub('urn:example:', '')}"
end
----

== Credits

This gem is developed, maintained and funded by
https://www.ribose.com[Ribose Inc.]

== License

The gem is available as open source under the terms of the
https://opensource.org/licenses/BSD-2-Clause[2-Clause BSD License].
