name: Test

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.0"
          - "2.7"
          - "2.6"
          - "2.5"
          - "2.4"

    steps:
      - name: Fetch source code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec
